language: java
notifications:
  hipchat:
    rooms:
      secure: lduu/26Xw+H6/Dj9qt3TMa71eSQRe6xVX05XYge4JawJERYNo1v9U+UMC4w2wbqN4vslbCd5fvD8n4+HlDi2fP2nOVJIs5xUuF5WlgnBXRkT83B6TvJAOgPo8kwPVt8mSgNJL3GPuaYkrl3qJlamlEIaaOkmGYvImC5Ee15RkdY=
deploy:
  provider: releases
  api_key:
    secure: Q9/soE4+2Zn4fiWoTiCPJOMPtNPJZEh5NZgkLNS/Vgpat3nCN2fcrlr/b4eZ5G8xkGKE9EkNhLcxLlTIrQy0lyvmSl+kzTZm9VSgAQyVdJ1VEzHTHzHqjK0pF1d6tcBblsdQiyLZxxWM+pzhpOFDr4YOH+PEYhKhq8SRXGWrzkE=
  file_glob: true
  file: build/distributions/*
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-ssrs-plugin
