language: java
notifications:
  hipchat:
    rooms:
      secure: lduu/26Xw+H6/Dj9qt3TMa71eSQRe6xVX05XYge4JawJERYNo1v9U+UMC4w2wbqN4vslbCd5fvD8n4+HlDi2fP2nOVJIs5xUuF5WlgnBXRkT83B6TvJAOgPo8kwPVt8mSgNJL3GPuaYkrl3qJlamlEIaaOkmGYvImC5Ee15RkdY=
deploy:
  provider: releases
  api_key:
    secure: hek90dw6rMT/o161AGadWPZZXjufDqVMetzHgw19DGfsZKIDuAJpwf/RH7XeOlJ6928R7I4v8M+u59ktERwbAukLBUh/aoEPC1Imz8ArQHgrhf+OIKUFG3xOA0Cg5T6kpHp9C3ANuYeX022J+Wnr3TBqN/NtmoS4/pf+3wbMND4=
  file: build/distributions/xld-ssrs-plugin-2.1.0.xldp
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-ssrs-plugin
