language: java
notifications:
  slack:
    secure: QfPb9aq/gpA0GBOxj/W+3LjECrgNc8BtynbCQhCy8OYOvZKDTZbIjW30x0/lBKCzAuE8JYHZH9xlFr8kUwFmBHbys8NsHM87LQR3bJkRYtD7XaKN0tVdTvl6+scCyXAol+RxystOsP7KvzZeaN832mfAfwpZEhrzKeDb8E7V8Sw=
deploy:
  provider: releases
  api_key:
    secure: Q9/soE4+2Zn4fiWoTiCPJOMPtNPJZEh5NZgkLNS/Vgpat3nCN2fcrlr/b4eZ5G8xkGKE9EkNhLcxLlTIrQy0lyvmSl+kzTZm9VSgAQyVdJ1VEzHTHzHqjK0pF1d6tcBblsdQiyLZxxWM+pzhpOFDr4YOH+PEYhKhq8SRXGWrzkE=
  file_glob: true
  file: build/distributions/*
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-ssrs-plugin
